version: '3.1'

services:
  db:
    image: mysql:8.0.23
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      ## O USUÁRIO PARA ENTRAR NO BANCO DE DADOS É: ROOT
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: school_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: db

volumes:
  dbbase: